### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Glinkis** [developit/karmatic#11]
I have been trying to get Typescript to play nicely with Karma for a while, and in the end I manage to get either nice stack traces in the console, or proper source mapping when debugging in the browser.

But never both.

So if Karmatic works with Typescript, could it also solve this problem?
And perhaps there could also be an example in the readme how to set it up?

**Comment by giladgray** [comment]
is there a way to use a custom webpack config via the CLI? (I see such a thing in the `configure` function, but no corresponding CLI option.) that should solve this, so I can configure my typescript loader.

**Comment by developit** [comment]
If you have a `webpack.config.js` or similar file, Karmatic will detect it and attempt to use any loaders/settings defined there.

**Comment by developit** [comment]
Closing as I've now used this a bunch of times - it "just works" if you have webpack setup to compile TS.

**Comment by Glinkis** [comment]
No, the issue still persists.
