### ISSUE TITLE
Unable to use 'React.createElement' as a pragma

### ISSUE THREAD

**Issue by ragingwind** [developit/karmatic#14]
`/** @jsx React.createElement */` doesn't apply to babel-plugin-transform-react-jsx. I assume that the [regex expression](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-jsx/src/index.js#L12) has some issue to parse 'React.createElement' pragma string. 

As a result, 'h' is always [enabled, default](https://github.com/developit/karmatic/blob/5eb2c64c0600e70b86900e7c50272edc2cff31d7/src/lib/babel-loader.js#L19) for pragma in karmatic as I tried to use`/** @jsx React.createElement */`

Any recommends?

**Comment by ragingwind** [comment]
I was digging more, regex has no problem

**Comment by developit** [comment]
hmm - that plugin is very widely used, I'd be surprised if it had such a basic issue.   Perhaps you're only adding that comment to one file, but using JSX in other files?  It's per-file.

Also, Babel only inspects the first JSX pragma in any given file ([see this example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABAQwBQEpEG8BQjED0AVEYgAIBWAzgB6IAWiRBeiqAPACYwBuhAfOgDcOAL44cxUpVqJgcOADoIAJwCmyKGoCiAGzUBbNWChMWHbnwKCROIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=react%2Cstage-1%2Ces2015-loose&prettier=true&targets=&version=6.26.0&envVersion=1.6.2)).
