### ISSUE TITLE
Deprecated packages are to be updated in package.json to actively supported packages

### ISSUE THREAD

**Issue by magnumthetyrant1** [developit/karmatic#20]
On running 
```bash
npm i -D karmatic
```
the following warnings are returned:
npm WARN deprecated karma-webpack@2.0.7: Deprecated due to publishing issue, use 2.0.8
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

**Comment by developit** [comment]
karma-webpack 2.0.8 is broken with karmatic, and node-uuid & nodemailer are out of our control.
