### ISSUE TITLE
Can I maintain this?

### ISSUE THREAD

**Issue by suchipi** [developit/karmatic#32]
Hello!

I'm interesting in maintaining (or co-maintaining) this project.

I'm pretty familiar with how it works, since I [forked it a while ago](https://github.com/suchipi/karmatic-nightmare).

I'd like to get https://github.com/developit/karmatic/pull/31 finished, and then maybe port some features over from my fork (jest-style reporter, `--dev-tools` flag, etc).

I'd also like to make a `--debug` flag that runs tests in the chrome debugger.

Are you interested in taking me on as a maintainer?

**Comment by developit** [comment]
yes yes yes! Absolutely. Jest parity would be amazing, `--debug` would be lovely.

**Comment by developit** [comment]
I added a [project board](https://github.com/developit/karmatic/projects/2?add_cards_query=is%3Aopen) for all these lovely things! We should add one for supporting Nightmare natively too.
