### ISSUE TITLE
Add `--watch` as an argument

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/karmatic#41]
Currently watch mode is done via a command: `karmatic watch **.test.js`. If a user defines this as an npm script than there is no easy way to toggle watch mode. The user would need to create a second script just for that.

```json
{
  "scripts": {
    "test": "karmatic tests/**test.js",
    "test:watch": "karmatic watch tests/**test.js"
  }
}
```

```bash
yarn test:watch
```

Compare this to with having a `--watch` argument:

```json
{
  "scripts": {
    "test": "karmatic tests/**test.js",
  }
}
```

```bash
yarn test --watch
```

**Comment by developit** [comment]
+1 to this - it's also another thing we need in order to get closer to parity with Jest's usage.
