### ISSUE TITLE
Webpack 5 Support

### ISSUE THREAD

**Issue by naoak** [developit/karmatic#67]
We have two PRs (developit/workerize-loader#101, developit/workerize-loader#114) for webpack 5 support in workerize-loader, but we can't test it unless we make karmatic webpack@5 compatible first. Now karma-webpack@5 supports webpack 5, so I think karmatic also could do it.

**Comment by developit** [comment]
Fixed in 507d48816b7411c9f13f24aae1cb686c4568560a.

FYI - `karma-webpack@5` has some major issues, but there's no alternative.
