### ISSUE TITLE
Istanbul/NYC integration for code coverage?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [developit/karmatic#9]
It's pretty common to use code coverage. Can Karmatic come with a config for it? Some thoughts:
* It would have to be off by default for performance. `--coverage`?
* Read settings from `"nyc"` in `package.json` / the other standard Istanbul settings tactics

**Comment by eliperelman** [comment]
If karmatic is reading from the webpack config, which will typically contain babel config via babel-loader, then loading istanbul should probably be done there instead.

For example, we plan on handling this in Neutrino with something like:

https://github.com/eliperelman/neutrino-dev/blob/1d1e34174fe86f4f740a1b912dc4dd537a332d9d/packages/karmatic/index.js#L8

In my opinion, it's probably best that karmatic is a wrapper around existing tools and doesn't try to expand its CLI presence by having to map flags to the configuration modification of these existing tools.
